syntax = "proto3";

package fences.v1;

service Fences {
  rpc CreateFence (CreateFenceRequest) returns (CreateFenceResponse);
  rpc DeleteFence (DeleteFenceRequest) returns (DeleteFenceResponse);
  rpc ModifyFence (ModifyFenceRequest) returns (ModifyFenceResponse);
}

message CreateFenceRequest {
  string name = 1;
  string creator_id = 2;
  string target_id = 3;
  int32 radius_in_meters = 4;
  double latitude = 5;
  double longitude = 6;
}

message CreateFenceResponse {
  string fence_id = 1;
}

message DeleteFenceRequest {
  string fence_id = 1;  
}

message DeleteFenceResponse {
}

message ModifyFenceRequest{
  string fence_id = 1;
  string name = 2;
  int32 radius_in_meters = 3;
  double latitude = 4;
  double longitude = 5;
}

message ModifyFenceResponse{
}
